CREATE TYPE "audits_type" AS ENUM (
  'delete',
  'update'
);

CREATE DATABASE compra_esperta;

CREATE TABLE "tbl_produtos" (
  "id_produto" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nm_prod" varchar(60) NOT NULL,
  "cd_ean_prod" varchar(12) NOT NULL,
  "ce_rfid" bigint,
  "ind_venda_dispositivo" bool NOT NULL,
  "ce_categoria_principal" bigint,
  "ce_categoria_secundaria" bigint,
  "updatedAt" timestamp,
  "createdAt" timestamp,
  "deletedAt" timestamp DEFAULT null,
  "isDeleted" bool DEFAULT false
);

CREATE TABLE "tbl_rfid" (
  "cp_id_dispositivo" bigint PRIMARY KEY NOT NULL,
  "ind_venda_dispositivo" bool NOT NULL DEFAULT false
);

CREATE TABLE "tbl_vendas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "produtoId" bigint,
  "cp_cod_estab" bigint,
  "updatedAt" timestamp,
  "createdAt" timestamp,
  "deletedAt" timestamp DEFAULT null,
  "isDeleted" bool DEFAULT false,
  "preco_venda" int,
  "valor_unitario" int,
  "quant_comprada" int
);

CREATE TABLE "tbl_categoria" (
  "cp_cod_categoria" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nm_categoria" varchar(20) NOT NULL,
  "updatedAt" timestamp,
  "createdAt" timestamp,
  "deletedAt" timestamp DEFAULT null,
  "isDeleted" bool DEFAULT false
);

CREATE TABLE "tbl_reposicao" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_funcionario" bigint,
  "id_produto" bigint,
  "data_reposicao" timestamp,
  "updatedAt" timestamp,
  "createdAt" timestamp,
  "deletedAt" timestamp DEFAULT null,
  "isDeleted" bool DEFAULT false
);

CREATE TABLE "tbl_fornecedores" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(60) NOT NULL,
  "document" varchar(60) NOT NULL,
  "isActive" bool NOT NULL DEFAULT true,
  "updatedAt" timestamp,
  "createdAt" timestamp,
  "deletedAt" timestamp DEFAULT null,
  "isDeleted" bool DEFAULT false
);

CREATE TABLE "tbl_estabelecimentos" (
  "cp_cod_estab" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nm_estab" varchar(60) NOT NULL,
  "cnpj_estab" varchar(60) DEFAULT null,
  "UF_estab" varchar(2) NOT NULL,
  "cidade_estab" varchar(5) NOT NULL,
  "updatedAt" timestamp,
  "createdAt" timestamp,
  "deletedAt" timestamp DEFAULT null,
  "isDeleted" bool DEFAULT false
);

CREATE TABLE "tbl_fornecimento" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_fornecedor" bigint,
  "id_produto" bigint,
  "data_venda" timestamp,
  "data_vencimento" timestamp,
  "valor_venda" int,
  "valor_unitario_produto" int
);

CREATE TABLE "tbl_funcionarios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(60) NOT NULL,
  "document" varchar(60) NOT NULL,
  "latitude" float NOT NULL,
  "longitude" float NOT NULL,
  "updatedAt" timestamp,
  "createdAt" timestamp,
  "deletedAt" timestamp DEFAULT null,
  "isDeleted" bool DEFAULT false
);

CREATE TABLE "tbl_audits" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "type" audits_type,
  "tableAffected" varchar(30),
  "updatedAt" timestamp,
  "createdAt" timestamp,
  "deletedAt" timestamp DEFAULT null,
  "isDeleted" bool DEFAULT false
);

ALTER TABLE "tbl_produtos" ADD FOREIGN KEY ("ce_categoria_principal") REFERENCES "tbl_categoria" ("cp_cod_categoria");

ALTER TABLE "tbl_produtos" ADD FOREIGN KEY ("ce_categoria_secundaria") REFERENCES "tbl_categoria" ("cp_cod_categoria");

ALTER TABLE "tbl_vendas" ADD FOREIGN KEY ("produtoId") REFERENCES "tbl_produtos" ("id_produto");

ALTER TABLE "tbl_vendas" ADD FOREIGN KEY ("cp_cod_estab") REFERENCES "tbl_estabelecimentos" ("cp_cod_estab");

ALTER TABLE "tbl_reposicao" ADD FOREIGN KEY ("id_funcionario") REFERENCES "tbl_funcionarios" ("id");

ALTER TABLE "tbl_reposicao" ADD FOREIGN KEY ("id_produto") REFERENCES "tbl_produtos" ("id_produto");

ALTER TABLE "tbl_fornecimento" ADD FOREIGN KEY ("id_fornecedor") REFERENCES "tbl_fornecedores" ("id");

ALTER TABLE "tbl_fornecimento" ADD FOREIGN KEY ("id_produto") REFERENCES "tbl_produtos" ("id_produto");